name: Issue and PR Bot

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize]

jobs:
  run-issue-pr-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Build and run Go script
      run: |
        go build -o issue_pr_bot main.go
        ./issue_pr_bot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        APP_ID: ${{ secrets.APP_ID }}
        INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
